; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.0-rc1"

projects[addthis][subdir] = "contrib"
projects[addthis][version] = "4.0-alpha1"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.0"

projects[autologout][subdir] = "contrib"
projects[autologout][version] = "2.0-beta1"

projects[blockify][subdir] = "contrib"
projects[blockify][version] = "1.2"

projects[boxes][subdir] = "contrib"
projects[boxes][version] = "1.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.1"

projects[calendar][subdir] = "contrib"
projects[calendar][version] = "3.4"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.0-beta2"

; Modules
projects[conditional_styles][subdir] = "contrib"
projects[conditional_styles][version] = "2.1"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta4"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[deploy][subdir] = "contrib"
projects[deploy][version] = "2.x-dev"

projects[diff][subdir] = "devel"
projects[diff][version] = "2.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc3+2-dev"

projects[entity_dependency][subdir] = "contrib"
projects[entity_dependency][version] = "1.0-alpha1"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0-rc3+2-dev"

projects[extlink][subdir] = "contrib"
projects[extlink][version] = "1.12"

projects[faq][subdir] = "contrib"
projects[faq][version] = "1.0-rc2"

projects[fast_404][subdir] = "contrib"
projects[fast_404][version] = "1.3"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta4"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[flood_control][subdir] = "contrib"
projects[flood_control][version] = "1.0"

projects[fusion_accelerator][subdir] = "contrib"
projects[fusion_accelerator][version] = "2.0-beta1"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.2"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.5"

projects[imce_mkdir][subdir] = "contrib"
projects[imce_mkdir][version] = "1.0"

projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "1.0"

projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

projects[node_export][subdir] = "contrib"
projects[node_export][version] = "3.0-rc4"

projects[nodequeue][subdir] = "contrib"
projects[nodequeue][version] = "2.0-beta1"

projects[og][subdir] = "contrib"
projects[og][version] = "1.4"

projects[og_forum_D7][subdir] = "contrib"
projects[og_forum_D7][version] = "1.1"

projects[og_menu][subdir] = "contrib"
projects[og_menu][version] = "2.1"

projects[og_views][subdir] = "contrib"
projects[og_views][version] = "1.0"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.2"

projects[password_policy][subdir] = "contrib"
projects[password_policy][version] = "1.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[pathauto_persist][subdir] = "contrib"
projects[pathauto_persist][version] = "1.3"

projects[purl][subdir] = "contrib"
projects[purl][version] = "1.0-beta1"

projects[recaptcha][subdir] = "contrib"
projects[recaptcha][version] = "1.7"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-beta4"

projects[services][subdir] = "contrib"
projects[services][version] = "3.1"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.2"

projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.0"

projects[spaces][subdir] = "contrib"
projects[spaces][version] = "3.0-alpha1"

projects[stage_file_proxy][subdir] = "devel"
projects[stage_file_proxy][version] = "1.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

; Modules
projects[text_resize][subdir] = "contrib"
projects[text_resize][version] = "1.7"

projects[token][subdir] = "contrib"
projects[token][version] = "1.2"

projects[token_filter][subdir] = "contrib"
projects[token_filter][version] = "1.1"

projects[USASearch][subdir] = "reisystems"
projects[USASearch][version] = "2.0+0-dev"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha3+39-dev"

projects[variable][subdir] = "devel"
projects[variable][version] = "1.2"

projects[views][subdir] = "contrib"
projects[views][version] = "3.3"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta6"

; Modules
projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.18"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.1"

projects[workbench_moderation][subdir] = "contrib"
projects[workbench_moderation][version] = "1.2"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.1"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0-rc1"

projects[fusion][version] = "2.0-beta2"

